Reader/Reader.php
Tests/StorageApiReaderTest.php

Renamd $downloadAS to $storage with allowed values 'local' or 's3'.

Renamed downloadTables param

---

composer.json

chci upgradnout PHP clienta v docker runneru a tim padem se musi zaroven upravit zavislost tady.
https://github.com/keboola/connection/issues/515

sapi client ^6.3

---

Configuration/Table.php
Tests/InputTableConfigurationTest.php

fixes https://github.com/keboola/docker-bundle/issues/256

feat: make where_op setting more permissive

---

Configuration/Table.php
Tests/Configuration/TableConfigurationTest.php

fix: make sure that table source is not empty

---

Reader/Reader.php
Tests/Reader/DownloadTablesDefaultTest.php

feat: improve info message, ref https://github.com/keboola/docker-bundle/issues/327

better message

---

Reader/Reader.php
Tests/Reader/DownloadFilesTest.php

fix: raise number of downloaded files to hotfix https://github.com/keboola/internal/issues/137

raise file limit

---

Reader/Reader.php
Tests/Reader/DownloadTablesDefaultTest.php

https://keboola.atlassian.net/browse/PS-213
feat: support components.max_export_size_bytes limit to cap table exports to CSV

limit export size

---

Dockerfile
Reader/LoadTypeDecider.php
Reader/NullWorkspaceProvider.php
Reader/Options/InputTableOptions.php
Reader/Reader.php
Reader/WorkspaceProviderInterface.php
Tests/Reader/DownloadFilesRedshiftTest.php
Tests/Reader/DownloadFilesTest.php
Tests/Reader/DownloadTablesAdaptiveTest.php
Tests/Reader/DownloadTablesDefaultTest.php
Tests/Reader/DownloadTablesOutputStateTest.php
Tests/Reader/DownloadTablesRedshiftTest.php
Tests/Reader/DownloadTablesS3DefaultTest.php
Tests/Reader/DownloadTablesWorkspaceTest.php
Tests/Reader/LoadTypeDeciderTest.php
Tests/Reader/NullWorkspaceProviderTest.php
Tests/Reader/Options/InputTableOptionsTest.php
Tests/Reader/ReaderTest.php

https://keboola.atlassian.net/browse/PS-284

Input mapping to workspace

---

Reader/Reader.php
Reader/Strategy/StrategyFactory.php

Viz https://travis-ci.org/github/keboola/docker-bundle/builds/704330766

Refactoring compatibility fixes

---

Configuration/Table.php
Tests/Configuration/TableConfigurationTest.php

odstraneny duplicitni type a pridany test na prazdny length 
https://keboola.slack.com/archives/CMTBFNLF8/p1600707705028000?thread_ts=1600097524.014800&cid=CMTBFNLF8

tests: add tests for empty length

---

Configuration/Table.php
Reader/LoadTypeDecider.php
Reader/Options/InputTableOptions.php
Tests/Configuration/TableConfigurationTest.php
Tests/Reader/DownloadTablesWorkspaceSnowflakeTest.php
Tests/Reader/LoadTypeDeciderTest.php
Tests/Reader/Options/InputTableOptionsTest.php
Tests/Reader/TableDefinitionResolverTest.php
Tests/Strategy/LocalStrategyTest.php

The workspaces api now supports an overwrite flag at the table level 
https://keboola.docs.apiary.io/#reference/workspaces/load-data/load-data

PS-1109 use overwrite flag

---

Reader/Options/InputTableOptions.php
Reader/Strategy/SnowflakeStrategy.php
Tests/Reader/DownloadTablesWorkspaceSnowflakeTest.php

overwrite wasn't being passed into the snowflake clone download.

PS-1142 fix clone overwrite

---

Reader/Strategy/SnowflakeStrategy.php
composer.json

https://keboola.atlassian.net/browse/PS-1489
needed for https://github.com/keboola/docker-bundle/pull/513

update storage api client

---

Reader/Reader.php
Reader/Strategy/SnowflakeStrategy.php
Tests/Reader/DownloadFilesRedshiftTest.php
Tests/Reader/DownloadFilesTest.php
Tests/Reader/DownloadFilesTestAbstract.php
Tests/Reader/DownloadTablesABSDefaultTest.php
Tests/Reader/DownloadTablesAdaptiveTest.php
Tests/Reader/DownloadTablesDefaultTest.php
Tests/Reader/DownloadTablesOutputStateTest.php
Tests/Reader/DownloadTablesRedshiftTest.php
Tests/Reader/DownloadTablesS3DefaultTest.php
Tests/Reader/DownloadTablesSynapseTest.php
Tests/Reader/DownloadTablesTestAbstract.php
Tests/Reader/DownloadTablesWorkspaceRedshiftTest.php
Tests/Reader/DownloadTablesWorkspaceSnowflakeTest.php
Tests/Reader/DownloadTablesWorkspaceSynapseTest.php
Tests/Reader/DownloadTablesWorkspaceTestAbstract.php
Tests/Reader/ReaderTest.php
composer.json

https://keboola.atlassian.net/browse/PS-1172
refactor to use client wrapper, release as new major version
depends on https://github.com/keboola/input-mapping/pull/64

Use Client wrapper

---

Reader/Reader.php
Reader/Strategy/ABSWorkspaceStrategy.php
Reader/Strategy/StrategyFactory.php
Reader/Strategy/SynapseStrategy.php
Reader/WorkspaceProviderInterface.php
Tests/Reader/DownloadTablesSynapseTest.php
Tests/Reader/DownloadTablesWorkspaceAbsTest.php
Tests/Reader/DownloadTablesWorkspaceSynapseTest.php
phpunit.xml.dist

This PR adds ABS workspace option and will download tables to the abs workspace

PS-1153 ABS workspace

---

Reader/Helper/SourceRewriteHelper.php
Reader/Options/InputTableOptions.php
Reader/Reader.php
Reader/Strategy/ABSStrategy.php
Reader/Strategy/ABSWorkspaceStrategy.php
Reader/Strategy/AbstractStrategy.php
Reader/Strategy/LocalStrategy.php
Reader/Strategy/RedshiftStrategy.php
Reader/Strategy/S3Strategy.php
Reader/Strategy/SnowflakeStrategy.php
Reader/Strategy/StrategyFactory.php
Reader/Strategy/SynapseStrategy.php
Tests/Reader/DownloadTablesDefaultTest.php
Tests/Reader/DownloadTablesRedshiftTest.php
Tests/Reader/DownloadTablesSynapseTest.php
Tests/Reader/DownloadTablesTestAbstract.php
Tests/Reader/DownloadTablesWorkspaceAbsTest.php
Tests/Reader/DownloadTablesWorkspaceSynapseTest.php
Tests/Reader/Helper/SourceRewriteHelperTest.php
Tests/Reader/ReaderTest.php
Tests/Strategy/LocalStrategyTest.php
Tests/Strategy/S3StrategyTest.php
phpunit.xml.dist

https://keboola.atlassian.net/browse/PS-1496

Read from dev branch if available

---

Reader/Helper/SourceRewriteHelper.php
Tests/Reader/DownloadTablesDefaultTest.php
Tests/Reader/DownloadTablesSynapseTest.php
Tests/Reader/DownloadTablesTestAbstract.php
Tests/Reader/DownloadTablesWorkspaceAbsTest.php
Tests/Reader/DownloadTablesWorkspaceSynapseTest.php
Tests/Reader/Helper/SourceRewriteHelperTest.php
Tests/Reader/ReaderTest.php
azure-pipelines.yml
bootstrap.php
composer.json
docker-compose.yml

https://keboola.atlassian.net/browse/PS-1534

Use branch name

---

Reader/Reader.php
Tests/Reader/DownloadFilesTest.php

slack: https://keboola.slack.com/archives/CQB468K63/p1606995849121400

fix: Pass format to the strategy

---

Reader/Helper/SourceRewriteHelper.php
Reader/Reader.php
Reader/Strategy/Files/AbstractFilesStrategy.php
Tests/Reader/DownloadFilesAbsWorkspaceTest.php
Tests/Reader/DownloadFilesRedshiftTest.php
Tests/Reader/DownloadFilesTest.php
Tests/Reader/Helper/SourceRewriteHelperTest.php
Tests/Reader/ReaderTest.php

Fixes: https://keboola.atlassian.net/browse/PS-1591 + https://keboola.atlassian.net/browse/PS-1592

Dev mode - load tables prefixed with branch id + restrict query filter for files

---

Reader/Helper/TagsRewriteHelper.php
Reader/Reader.php
Reader/Strategy/Files/AbstractFilesStrategy.php
Tests/Reader/DownloadFilesAbsWorkspaceTest.php
Tests/Reader/DownloadFilesTest.php
Tests/Reader/Helper/TagsRewriteHelperTest.php

Fixes: https://keboola.atlassian.net/browse/PS-1562

Reader::getFiles - rewrite file tags for dev branch

---

Reader/Reader.php
Tests/Reader/DownloadFilesAbsWorkspaceTest.php
Tests/Reader/DownloadFilesTest.php

Fixes: https://keboola.atlassian.net/browse/PS-1573

Reader::getFiles - Restrict processed_tags for dev branch

---

src/Helper/InputBucketValidator.php
src/Helper/SourceRewriteHelper.php
src/Reader.php
src/Table/Options/ReaderOptions.php
tests/Functional/DownloadTablesABSDefaultTest.php
tests/Functional/DownloadTablesAdaptiveTest.php
tests/Functional/DownloadTablesDefaultTest.php
tests/Functional/DownloadTablesOutputStateTest.php
tests/Functional/DownloadTablesRedshiftTest.php
tests/Functional/DownloadTablesS3DefaultTest.php
tests/Functional/DownloadTablesSynapseTest.php
tests/Functional/DownloadTablesWorkspaceAbsTest.php
tests/Functional/DownloadTablesWorkspaceRedshiftTest.php
tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php
tests/Functional/DownloadTablesWorkspaceSynapseTest.php
tests/Helper/InputBucketValidatorTest.php
tests/Helper/SourceRewriteHelperTest.php
tests/ReaderTest.php
tests/Table/Options/ReaderOptionsTest.php

https://keboola.atlassian.net/browse/PS-1694

feat: disallow dev buckets in input mapping

---

src/File/Strategy/ABSWorkspace.php
src/File/Strategy/AbstractStrategy.php
src/File/Strategy/Local.php
tests/Functional/DownloadFilesAbsWorkspaceTest.php

https://keboola.atlassian.net/browse/PS-1646

Remove duplicate file id 

---

src/Reader.php
tests/Functional/DownloadFilesTest.php

Required for https://github.com/keboola/output-mapping/pull/78

PS-1798 Allow query and processed_tags for branches

---

src/Helper/BuildQueryFromConfigurationHelper.php
src/Helper/TagsRewriteHelper.php
tests/Functional/DownloadFilesTest.php
tests/Functional/DownloadFilesTestAbstract.php
tests/Helper/TagsRewriteHelperTest.php

good morning @odinuv, here's a brain walloper for breakfast :-).  please let me know if there are some cases I've overlooked in the test, I'm sure there are.

PS-1798 processing processed tags process

---

src/Table/Options/InputTableOptions.php

https://keboola.atlassian.net/browse/PS-1780

Fix arguments order in `implode` calls

---

src/File/Strategy/AbstractStrategy.php
src/Reader.php
src/State/InputFileStateList.php
tests/Functional/DownloadFilesAdaptiveTest.php
tests/Functional/DownloadFilesTest.php

I tried to reduce the number of conditions (if changed_since = adaptive) so that the handling occurs at (ideally) a single place. What do you think?

reduce number of conditions

---

src/File/Strategy/AbstractStrategy.php
tests/Functional/DownloadFilesAdaptiveTest.php

It took me a while to understand what's happening there so I tried to make it clearer. Not sure if successfully - how does this appeal to you?

slightly different approach

---

src/File/Strategy/AbstractStrategy.php
tests/Functional/DownloadFilesAdaptiveTest.php

first part of https://keboola.atlassian.net/browse/PS-2179

PS-2179 broken adaptive files im

---

src/Helper/BuildQueryFromConfigurationHelper.php
tests/Functional/DownloadFilesAdaptiveTest.php
tests/Helper/BuildQueryFromConfigurationHelperTest.php

Should have done it this way the first time round 🤦

PS-2179 bad changed_since syntax

---

composer.json
src/File/Strategy/ABSWorkspace.php
src/Table/Strategy/ABSWorkspace.php
src/Table/Strategy/Snowflake.php
src/Table/Strategy/Synapse.php
tests/Functional/DownloadFilesAbsWorkspaceTest.php
tests/Functional/DownloadTablesWorkspaceTestAbstract.php

https://keboola.atlassian.net/browse/PS-2036
U vsech nalezenych usage workspaces API jsem prehodil na branchAware klienta. Neco je pres `Workspaces` tridu, neco navostro pres URL, tak snad jsem chytil vsechno.

PS-2036 Use branchAware API client for Workspaces API

---

src/Configuration/File.php
src/File/Strategy/ABSWorkspace.php
src/File/Strategy/AbstractStrategy.php
src/File/Strategy/Local.php
src/File/StrategyInterface.php
tests/Configuration/FileConfigurationTest.php
tests/Functional/DownloadFilesAbsWorkspaceTest.php
tests/Functional/DownloadFilesAdaptiveTest.php
tests/Functional/DownloadFilesRedshiftTest.php
tests/Functional/DownloadFilesTest.php
tests/Functional/DownloadTablesWorkspaceSynapseTest.php

https://keboola.atlassian.net/browse/PS-2160

feat: support overwrite flag on ABS workspaces

---

src/Helper/ManifestCreator.php

https://keboola.atlassian.net/browse/PS-2007
Reuse table/column metadata from existing tableInfo when saving table manifest

PS-2007 Table manifest write optimization

---

src/Helper/LoadTypeDecider.php
tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php
tests/Helper/LoadTypeDeciderTest.php

https://keboola.atlassian.net/browse/PS-2378

Don't use clone loading when filtered alias is used

---

src/Reader.php
src/Table/Options/ReaderOptions.php
src/Table/Strategy/ABS.php
src/Table/Strategy/ABSWorkspace.php
src/Table/Strategy/AbstractDatabaseStrategy.php
src/Table/Strategy/AbstractStrategy.php
src/Table/Strategy/Local.php
src/Table/Strategy/S3.php
src/Table/Strategy/Synapse.php
src/Table/StrategyInterface.php
tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php
tests/Functional/DownloadTablesWorkspaceSynapseTest.php

https://keboola.atlassian.net/browse/PS-2615

PS-2615 obey preserve

---

composer.json
tests/Functional/DownloadTablesOutputTest.php

Part of https://keboola.atlassian.net/browse/PS-2638

use sapi client >= 12.6

---

src/Table/Strategy/AbstractDatabaseStrategy.php
tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php

The real fix will need to be made on the connection, but this should put a stop to it for now.
vice https://keboola.atlassian.net/wiki/spaces/TECH/pages/2383511594/Input+mapping+to+workspace+Consolidation

PS-2335 Fix Race Condition

---

src/Table/Strategy/AbstractDatabaseStrategy.php
tests/Functional/DownloadTablesWorkspaceRedshiftTest.php
tests/Functional/DownloadTablesWorkspaceSnowflakeTest.php

https://keboola.atlassian.net/browse/PS-2781

PS-2781 Return also results for clones

---

composer.json
src/File/Strategy/ABSWorkspace.php
tests/Functional/DownloadFilesAbsWorkspaceTest.php
tests/Functional/DownloadTablesWorkspaceAbsTest.php

Fixes: https://keboola.atlassian.net/browse/PS-3135

create blob storage client via Keboola\FileStorage\Abs\ClientFactory

---

composer.json
phpunit.xml.dist
src/Reader.php
src/Staging/StrategyFactory.php
tests/Functional/DownloadFilesAbsWorkspaceTest.php
tests/Functional/DownloadFilesAdaptiveTest.php
tests/Functional/DownloadFilesRedshiftTest.php
tests/Functional/DownloadFilesTest.php
tests/Functional/DownloadFilesTestAbstract.php
tests/Functional/DownloadTablesDefaultTest.php
tests/Functional/DownloadTablesSynapseTest.php
tests/Functional/DownloadTablesTestAbstract.php
tests/Functional/DownloadTablesWorkspaceAbsTest.php
tests/Functional/DownloadTablesWorkspaceSynapseTest.php
tests/Helper/InputBucketValidatorTest.php
tests/Helper/SourceRewriteHelperTest.php
tests/Helper/TagsRewriteHelperTest.php
tests/ReaderTest.php
tests/Staging/StrategyFactoryTest.php
tests/Table/Strategy/AbstractStrategyTest.php
tests/Table/Strategy/ExasolTest.php

https://keboola.atlassian.net/browse/PS-3098
Refactored tests because the client wrapper is now immutable and branch cannot be set after construction.
Depends on https://github.com/keboola/storage-api-php-client-branch-wrapper/pull/9

Update Client wrapper

---

src/Staging/StrategyFactory.php
src/Table/Strategy/Teradata.php
tests/Staging/StrategyFactoryTest.php
tests/Table/Strategy/TeradataTest.php

Fixes: https://keboola.atlassian.net/browse/PS-3400

Teradata Strategy
